image:
  pullPolicy: Always

server:
  enabled: true

  port: 3000

  istio:
    injected: true

  liveness:
    delay: 20

  readiness:
    path: /health_check
    delay: 20

  resources:
    requests:
      cpu: 10m
      memory: 1Gi
    limits:
      memory: 2Gi

service:
  enabled: true

virtualService:
  enabled: true

  gateways:
    - backend-gateway/backend-gateway
    - geni/gateway

  hosts:
    - geni.ktbs.xyz
    - geni.kitabisa.xyz

  routes:
    - match:
        - uri:
            prefix: /smocker/
      retries:
        attempts: 3
        perTryTimeout: 15s
        retryOn: gateway-error
      rewrite:
        uri: /
      route:
        - destination:
            host: smocker-server-stg
            port:
              number: 80
          weight: 100

autoscaling:
  minReplicas: 1
  maxReplicas: 1
