repositories:
  - name: kitabisa
    url: {{ requiredEnv "CHARTS_REPOSITORY" }}
    oci: true

releases:
  - name: {{ requiredEnv "APP_NAME" }}-server-{{ requiredEnv "ENV_NAME" }}
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: app
      type: main
    chart: kitabisa/app
    version: ~1.1.0-rc
    values:
      - {{ requiredEnv "ENV" }}/server.yaml
      - values.yaml.gotmpl

  - name: {{ requiredEnv "APP_NAME" }}-debugger
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: debugger
      type: optional
    chart: kitabisa/debugger
    installed: false
