name: CI

on:
  pull_request:
    types: [assigned, unassigned, opened, synchronize, edited, ready_for_review, reopened]
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && github.actor != 'renovate[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Danger JS
        run: bun danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  semgrep:
    needs: ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep ci
