name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
        if: ${{ steps.release.outputs.release_created }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kitabisa'
        if: ${{ steps.release.outputs.release_created }}

      - run: bun install --frozen-lockfile
        if: ${{ steps.release.outputs.release_created }}

      - run: bun run build
        if: ${{ steps.release.outputs.release_created }}

      - run: bun run cli:build
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
