name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.KITABISA_RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.KITABISA_RELEASE_BOT_APP_PRIVATE_KEY }}

      - name: Release please
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ steps.app-token.outputs.token }}
