name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Creating release PR
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node

      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        run: bun install --frozen-lockfile
        if: ${{ steps.release.outputs.release_created }}

      - name: Build package
        run: bun pkg:build
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish package
        run: bun pkg:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
